import { StyleSheet, Dimensions, Platform, StatusBar } from 'react-native';

const { width } = Dimensions.get('window');
const STATUSBAR_HEIGHT = Platform.OS === 'android' ? (StatusBar.currentHeight || 36) : 0;

export default StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#0F2744' },
  header: {
    backgroundColor: '#0F2744',
    paddingHorizontal: 20,
    paddingTop: STATUSBAR_HEIGHT + 16, // Adds exact status bar spacing for Android
    paddingBottom: 24,
  },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  brand: { flexDirection: 'column' },
  brandName: { fontSize: 22, fontWeight: '900', color: '#fff', letterSpacing: -0.5 },
  brandSub: { fontSize: 11, color: '#3b82f6', fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.5 },
  headerRight: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  notifBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255,255,255,0.08)', justifyContent: 'center', alignItems: 'center' },
  notifIcon: { fontSize: 18 },
  avatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#3b82f6', justifyContent: 'center', alignItems: 'center' },
  avatarText: { color: '#fff', fontWeight: '800', fontSize: 13 },
  nameRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 8, marginBottom: 16 },
  lawyerName: { fontSize: 16, fontWeight: '800', color: '#fff' },
  stars: { color: '#fbbf24', fontSize: 12 },
  verifiedPill: { backgroundColor: '#dcfce7', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 50 },
  verifiedText: { color: '#166534', fontSize: 10, fontWeight: '800' },
  statsRow: { flexDirection: 'row', gap: 8 },
  statChip: { flex: 1, backgroundColor: 'rgba(255,255,255,0.06)', borderRadius: 12, padding: 12, alignItems: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  statNum: { fontSize: 18, fontWeight: '800', color: '#fff' },
  statLabel: { fontSize: 10, color: 'rgba(255,255,255,0.6)', marginTop: 2, fontWeight: '500' },
  scroll: { flex: 1, backgroundColor: '#F5F3EF', borderTopLeftRadius: 28, borderTopRightRadius: 28 },
  scrollContent: { padding: 20, paddingBottom: 40, gap: 16 },
  sectionHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 8 },
  sectionLabel: { fontSize: 15, fontWeight: '800', color: '#0F2744', letterSpacing: -0.2 },
  seeAllText: { fontSize: 12, color: '#3b82f6', fontWeight: '700' },
  reqCard: { backgroundColor: '#fff', borderRadius: 16, padding: 16, borderWidth: 1, borderColor: '#ece9e4' },
  reqTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
  reqName: { fontSize: 14, fontWeight: '700', color: '#1a1a1a' },
  badgeNew: { fontSize: 9, fontWeight: '800', color: '#fff', backgroundColor: '#ef4444', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 50, textTransform: 'uppercase' },
  reqDesc: { fontSize: 12, color: '#666', lineHeight: 16 },
  pipeItem: { backgroundColor: '#fff', borderRadius: 16, padding: 16, borderWidth: 1, borderColor: '#ece9e4' },
  pipeTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
  pipeLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  pipeDot: { width: 8, height: 8, borderRadius: 4 },
  pipeTitle: { fontSize: 13, fontWeight: '700', color: '#1a1a1a' },
  pipeSub: { fontSize: 11, color: '#888' },
  statusBadge: { fontSize: 9, fontWeight: '800', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6, textTransform: 'uppercase' },
  badgeBlue: { backgroundColor: '#dbeafe', color: '#1e40af' },
  badgeAmber: { backgroundColor: '#fef3c7', color: '#92400e' },
  badgeGreen: { backgroundColor: '#dcfce7', color: '#166534' },
  quickGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  quickCard: { width: (width - 52) / 2, backgroundColor: '#fff', borderRadius: 16, padding: 16, borderWidth: 1, borderColor: '#ece9e4' },
  quickIcon: { fontSize: 22, marginBottom: 8 },
  quickTitle: { fontSize: 13, fontWeight: '700', color: '#1a1a1a' },
  quickSub: { fontSize: 10, color: '#888', marginTop: 2 },
  bottomNav: { flexDirection: 'row', backgroundColor: '#fff', borderTopWidth: 1, borderTopColor: '#ece9e4', paddingVertical: 8, paddingBottom: 20, justifyContent: 'space-around' },
  navItem: { alignItems: 'center', justifyContent: 'center', paddingVertical: 4 },
  navIcon: { fontSize: 18, marginBottom: 2 },
  navLabel: { fontSize: 10, color: '#999', fontWeight: '600' },
  navLabelActive: { color: '#0F2744' },
  navActiveDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: '#0F2744', marginTop: 3 },
});